apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 297601880274.dkr.ecr.us-east-1.amazonaws.com/order-service:cec7c3e003e2c35e86c85bccc928110620df75ae
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: "development"

            - name: PORT
              value: "3004"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: ORDERS_DB_URL
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3002"

            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3003"

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "250m"

          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: boutique

spec:
  type: ClusterIP

  selector:
    app: order-service

  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
